# Generated by Django 4.2.1 on 2023-05-25 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200, verbose_name='Kliento pavadinimas')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Įmonės kodas')),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='PVM kodas')),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Adresas')),
                ('email_address', models.EmailField(blank=True, max_length=100, null=True, verbose_name='El. paštas')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono numeris')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Sukurtas')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Redaguotas')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=500, verbose_name='Prekės pavadinimas')),
                ('product_code', models.CharField(max_length=50, verbose_name='Prekės kodas')),
                ('product_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Prekės aprašymas')),
                ('product_quantity', models.FloatField(blank=True, null=True, verbose_name='Kiekis')),
                ('product_price', models.FloatField(blank=True, null=True, verbose_name='Kaina')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Sukurta')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Redaguota')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=500, verbose_name='Paslaugos pavadinimas')),
                ('service_code', models.CharField(max_length=50, verbose_name='Paslaugos kodas')),
                ('service_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Paslaugos aprašymas')),
                ('service_quantity', models.FloatField(blank=True, null=True, verbose_name='Kiekis')),
                ('service_price', models.FloatField(blank=True, null=True, verbose_name='Kaina')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Sukurtas')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Redaguotas')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_name', models.CharField(max_length=200, verbose_name='Pavadinimas')),
                ('invoice_number', models.IntegerField(verbose_name='Sąskaitos numeris')),
                ('due_date', models.DateField(verbose_name='Apmokėti iki')),
                ('payment_terms', models.CharField(choices=[('1d', '1 diena'), ('3d', '3 dienos'), ('5d', '5 dienos'), ('7d', '7 dienos'), ('14d', '14 dienų'), ('30d', '30 dienų'), ('60d', '60 dienų')], default='30d', max_length=10)),
                ('invoice_status', models.CharField(choices=[('l', 'Laukiama apmokėjimo'), ('a', 'Apmokėta'), ('p', 'Pradelsta')], default='l', max_length=20)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Sukurta')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Redaguota')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvoiceApp.client')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvoiceApp.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvoiceApp.service')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
