# Generated by Django 4.2.1 on 2023-06-08 22:04

import InvoiceApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Apmokėti iki'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_name',
            field=models.CharField(blank=True, default='INV', max_length=200, null=True, verbose_name='Serija'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, default=InvoiceApp.models.Invoice.increment_invoice_number, max_length=10, null=True, verbose_name='Sąskaitos numeris'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('l', 'Laukiama apmokėjimo'), ('a', 'Apmokėta'), ('p', 'Pradelsta')], default='l', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('1d', '1 diena'), ('3d', '3 dienos'), ('5d', '5 dienos'), ('7d', '7 dienos'), ('14d', '14 dienų'), ('30d', '30 dienų'), ('60d', '60 dienų')], default='30d', max_length=10, null=True),
        ),
    ]
