# Generated by Django 4.2.1 on 2023-06-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_name',
            field=models.CharField(default='INV', max_length=200, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=10, verbose_name='Sąskaitos numeris'),
        ),
    ]
