# Generated by Django 4.2.1 on 2023-06-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceApp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='responsibilities',
            field=models.CharField(default=0, max_length=200, verbose_name='Pareigos'),
            preserve_default=False,
        ),
    ]
