# Generated by Django 4.2.1 on 2023-06-13 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceApp', '0002_alter_invoice_due_date_alter_invoice_invoice_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_total',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('1', '1 diena'), ('3', '3 dienos'), ('5', '5 dienos'), ('7', '7 dienos'), ('14', '14 dienų'), ('30', '30 dienų'), ('60', '60 dienų')], default='30', max_length=10, null=True),
        ),
    ]
