# Generated by Django 4.2.1 on 2023-06-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceApp', '0003_profile_responsibilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=0, max_length=200, verbose_name='Telefono numeris'),
            preserve_default=False,
        ),
    ]
