# Generated by Django 4.2.1 on 2023-06-13 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceApp', '0003_invoice_invoice_total_alter_invoice_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvoiceApp.client'),
        ),
    ]
