# Generated by Django 4.2.1 on 2023-06-14 18:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceApp', '0004_alter_invoice_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_products_services',
            field=models.TextField(default=0, verbose_name='Sąskaitos prekės/paslaugos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvoiceApp.client', verbose_name='Klientas'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('l', 'Laukiama apmokėjimo'), ('a', 'Apmokėta'), ('p', 'Pradelsta')], default='l', max_length=20, null=True, verbose_name='Statusas'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_total',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Sąskaitos suma'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('1', '1 diena'), ('3', '3 dienos'), ('5', '5 dienos'), ('7', '7 dienos'), ('14', '14 dienų'), ('30', '30 dienų'), ('60', '60 dienų')], default='30', max_length=10, null=True, verbose_name='Apmokėjimo terminas'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvoiceApp.product', verbose_name='Prekė'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvoiceApp.service', verbose_name='Paslauga'),
        ),
    ]
