# Generated by Django 4.2.1 on 2023-06-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceApp', '0005_invoice_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='employee',
            new_name='user',
        ),
    ]
